export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENCE_INDEX = 'SET_CURRENCE_INDEX'

export const SET_SINGER_ADD = 'SET_SINGER_ADD'

export const SET_DIC = 'SET_DIC'

export const SET_TOP_LIST = 'SET_TOP_LIST'
